# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Chapter04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '15.0'

  pod 'SideMenu', '~> 6.0'
  # Pods for Chapter04

end
