# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'imagePickerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '13.0'
  use_frameworks!
  pod 'RxSwift'
  # Pods for imagePickerExample
  
  target 'imagePickerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'imagePickerExampleUITests' do
    # Pods for testing
  end

end
